framework <- list()
framework[[atlas$locus[1]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5", "Intron 5", "Exon 6", "Intron 6", "Exon 7", "Intron 7", "Exon 8", "3'UTR") 
framework[[atlas$locus[2]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5", "Intron 5", "Exon 6", "Intron 6", "Exon 7","3'UTR")
framework[[atlas$locus[3]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5", "Intron 5", "Exon 6", "Intron 6", "Exon 7", "Intron 7", "Exon 8","3'UTR")
framework[[atlas$locus[4]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","3'UTR")
framework[[atlas$locus[5]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5","3'UTR")
framework[[atlas$locus[6]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","3'UTR")
framework[[atlas$locus[7]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5", "Intron 5", "Exon 6","3'UTR")
framework[[atlas$locus[8]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5", "Intron 5", "Exon 6","3'UTR")
framework[[atlas$locus[9]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5", "Intron 5", "Exon 6","3'UTR")
framework[[atlas$locus[10]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5", "Intron 5", "Exon 6","3'UTR")
framework[[atlas$locus[11]]]<-c("5'UTR", "Exon 1", "Intron 1","Exon 2","Intron 2","Exon 3", "Intron 3", "Exon 4","Intron 4", "Exon 5", "Intron 5", "Exon 6","3'UTR")  
save(framework,file="framework.rda")
